azure_storage_connectionstring: "INSERT SUBSCRIPTION HERE"
patients_container_name: "patients"
staff_container_name: "staff"
stafflogin_container_name: "stafflogin"
source_folder: "/Users/matte/OneDrive/Desktop/Projects/Python/Hackhive2024/upload"
